version: "3.8"

services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "3333:3333"
    networks: 
     - network-backend
  
  mysql:
    image: mysql:5.7
    restart: always
    volumes: 
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment: 
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  my-db: